In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
a.dtype

dtype('int64')

In [9]:
a.dtype

dtype('int64')

In [10]:
a.size*a.itemsize


24

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print (a)

[[1 2 3]
 [4 5 6]]


In [12]:
a[1,2]

6

In [13]:
#sepecific row
a[1,:]

array([4, 5, 6])

In [14]:
#specific coloumn
a[:,1]

array([2, 5])

In [15]:
#All zeros matrix
np.zeros((2,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [16]:
np.full(a.shape,9)

array([[9, 9, 9],
       [9, 9, 9]])

In [17]:
np.full_like(a,9)

array([[9, 9, 9],
       [9, 9, 9]])

In [18]:
np.random.rand(4,2)

array([[0.37615023, 0.64907333],
       [0.61354954, 0.85411192],
       [0.73657608, 0.12574431],
       [0.96124763, 0.52713862]])

In [19]:
np.identity(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

##Excersise

In [20]:
a=np.ones((5,5))
print(a)

z=np.zeros((3,3))
z[1,1]=9
print(z)

a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
b=a.copy()
b[0][0]=100
print(b)
print(a)

[[100.   1.   1.   1.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   0.   9.   0.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Basic python copying


In [22]:
# b=b**4
print(b)

[[100.   1.   1.   1.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   0.   9.   0.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.]]


In [23]:
print(b)

[[100.   1.   1.   1.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   0.   9.   0.   1.]
 [  1.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.]]


In [24]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]
